#!/bin/bash

echo "Testing........"
OUTPUT="$(go test ./...)"
if [ $? -ne 0 ]
then
	echo "${OUTPUT}"
	echo "Failed to run tests. Please check the output of"
	echo "go test or run commit with --no-verify if you know"
	echo "what you are doing."
	exit 1
fi